### ISSUE TITLE
Should we remove the `yarn` dependency?

### ISSUE THREAD

**Issue by ndorfin** [NZTechRally/nztechrally.com#11]
I'm not sure what the benefits of using Yarn v1 are (besides checksum checks), but I do know having to install it on one's system is another bump in the road to running a project, especially if one is a junior.

NPM has come a long way, and is slightly faster than Yarn v1 now.

[This article on 'NPM vs. Yarn vs. PNPM'](https://blog.logrocket.com/javascript-package-managers-compared/) was interesting reading, but phew, I know I don't want to use _another_ new package manager, how about you? :P

With your permission, I'll remove the yarn dependency, and add the necessary boilerplate for NPM/Node version settings.

**Comment by praesongprasit** [comment]
Yup sounds great to me. Especially now that Eleventy's latest version is doing a lot on its own.
